### ISSUE TITLE
[Feature request] Implementing simkl tracker and watchlists

### ISSUE THREAD

**Issue by IamJanarthan** [Tikipeter/tikipeter.github.io#113]
Simkl is grown to be a good database and tracker which works much better for anime, is there any way you can add it to fenlight

**Comment by hcgiub001** [comment]
I've been looking into this and was meaning to bring it up to Tikipeter attention.
This is what POV is using for it's anime, I'm not sure if Tikipeter looked through that API but I learnt it's not so many api calls

in simkl api you have this
https://simkl.docs.apiary.io/#reference/anime/trending/get-trending-anime-series

for this call you can request all animes in the list to have the tmdb id by using this
https://api.simkl.com/anime/trending/?extended=overview,metadata,tmdb,genres,trailer&client_id=***

I don't know if you can get any other list to have tmdb ids, I thought this part
![Screenshot (504)](https://github.com/user-attachments/assets/22e48cfd-9e25-419c-a3d2-fcf2971cb37d)

meant we can use the extended call to grab tmdb from any filter we create on 
best section.

this conversation is relevant from POV dev
https://www.reddit.com/r/Addons4Kodi/comments/1epspuz/comment/lhosm3g/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

I also found out how to get correct season/episode data from TMDB , I've wanted to bring this to your attention Peter but thought to let other issues get completed, but since someone mentioned anime (which I would love to get) I'll make an issue with the method to get correct anime (and other shows) season/episode listing
