### ISSUE TITLE
[Bug] Fen Light - HBO Max Provider No Results

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/tikipeter.github.io#115]
Hi Tikipeter,

I've noticed that in:
Movies/TV Shows --> Providers --> HBO Max

There are no results for both movies and tv shows menus. (On TV Shows --> Networks --> HBO Max it works)

I saw no relevant line in kodi.log. 

Twilight

**Comment by Tikipeter** [comment]
I've rechecked with fresh data from TMDb, and `384` is still the correct id for HBO Max.

I can' see any reason why TMDb are not returning any results for it.

`{'page': 1, 'results': [], 'total_pages': 1, 'total_results': 0}`

Maybe it is an issue on their end. I'll wait a while and see if it resolves itself.

**Comment by Tikipeter** [comment]
I'm going to close this because there doesn't seem to be anything I can do to fix it, and I've got too many open issues for my comfort.

Let me know with a new issue if this doesn't sort itself out in due time. There's a cache of 48 hours on the results of a call for this info, so if you want to check it before that cache runs out, "Clear Lists Cache".
