### ISSUE TITLE
[FEATURE REQUEST] Add Debrid Media Manager as source

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#129]
Hey Tikipeter, Could you please add Debrid Media Manager as a source.
I watch lots of Kdrama and found DMM have lots more sources.

I've also learnt that people using Stremio are able to use DMM so doing some research I found the addon to be called comet

this is their github
https://github.com/g0ldyy/comet

and inside it
![image](https://github.com/user-attachments/assets/1557d889-614f-483b-af8f-f002ebebb374)

[Zilean](https://github.com/iPromKnight/zilean) ([DMM](https://hashlists.debridmediamanager.com/) Scraper) support for even more results

so Adding support for Zilean seems like we could get DMM as a source.

Would love if you could consider adding it, even later, plus as I've mentioned to you before It was able to bring up episodes 
![image](https://github.com/user-attachments/assets/67e2d2ae-5276-47fd-ba87-566556935daa)

atm I have to find the source, then add it to my cloud, then go through the menus to delete two caches then find the show again and I can resume, plus at the time didn't realise we could have DMM as a source, until someone mentioned they use Comet that uses DMM
Would be so amazing for kdrama lovers! and anime lovers since it's even pulling some anime, especially chinese anime that torrentio or nya can't pull.
Thanks for your consideration

**Comment by Tikipeter** [comment]
That's a cocojoe (Cocoscrapers) request. I can only have personal type scrapers default with Fen Light.

I think he has issues closed, so I'll do my best to get into contact with him. Sometimes it's quite difficult.

**Comment by hcgiub001** [comment]
if this is added with cocoscraper that would be insane, thanks for trying!

**Comment by hcgiub001** [comment]
not sure if you already spoke with cocoscraper dev and this your doing but an update from umbrella dev 
[This SHOULD be in the next cocoscrapers update.](https://www.reddit.com/r/Addons4Kodi/comments/1fp9b2t/comment/lq1g0s4/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

Pretty happy about this. it really is a game changer for kdrama and completes anime but also if torrentio is down, this is just as capable.

**Comment by Tikipeter** [comment]
Umbrella dev and I have been talking about this yesterday. 

Just a couple of things to iron out tonight when I wake up.

And we're still trying to determine whether a debrid token is necessary.  Sometimes it works without, sometimes not. 

It's a finicky service but it's giving decent results overall.

**Comment by hcgiub001** [comment]
Nice work! looking forward to it :)

**Comment by TwilightMercy** [comment]
> It's a finicky service but it's giving decent results overall.

Good luck!
Are you taking about Comet stremio addon itself as a source?

Or Debrid Media Manager source through "Zilean" hashlists scraper? (Which Comet addon uses?

**Comment by Tikipeter** [comment]
Yeah I've worked with both of them, and regularly work with Umbrella dev.

We've got it working well, umbrella and I. We needed to solve the pack results often not working due to api limits, and (at least for now) we are not using any debrid tokens. This will depend on whether Comet starts complaining that the debrid token sent is invalid, as we are just sending an empty string currently. It's working fine though.

We'll let kodifitzwell know of the changes once more testing is done. This will fix his issues of rate limits and stop him needing to input a debrid token and set a debrid provider in the settings.

Just got to test it more. It may well be off by default too. Haven't decided yet.

**Comment by tundrablasen** [comment]
Even though this is now just Tikis Repo, I want to thank you all three what you do for the community. As I understand having comet in the scraper is a blessing. 

For me especially because of the [RTN. Smart Torrent Ranking](https://github.com/dreulavelle/rank-torrent-name). I can finally then set up rules that only the best scene releases from respected groups get played and cached on RD.

i will follow the [Trash Guides for Radarr (movies)](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/#hq-release-groups) rules, as well as the [Trash Guides counterpart for Sonarr (TV shows)](https://trash-guides.info/Sonarr/sonarr-collection-of-custom-formats/#hq-source-groups)

This was the biggest reason for me to stick with my NAS and my Sonarr/Radarr home server. Thankfully Fen Light has amazing support for Local Sources as well. So Fen Light is already amazingly utilizing my NAS.

**Comment by hcgiub001** [comment]
I've been testing this and the results we are getting are great! I've noticed elfhosted is taken off though. but still it's a great addition, great work you guys! thank you
