### ISSUE TITLE
TV Shows in Progress not showing certain shows

### ISSUE THREAD

**Issue by TechXXX** [Tikipeter/tikipeter.github.io#130]
Hiya Peter, great addon you made here, love the auto-scrape episode feature but that's not what I'm writing about. I actually went through this exact same problem with Umbrella but unfortunately he closed the ticket so I can't link to it (he fixed it back then btw). So the thing is, Fen Light isn't showing progress shows as it shows on the website, best to illustrate; here's the trakt.tv website under progress: 

<img width="1709" alt="image" src="https://github.com/user-attachments/assets/25f68d2f-a8a6-4121-b534-defd4fbb3ec0">

and here's Fen Light under TV Shows in Progress: 

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/cf9473af-8557-40ca-a02d-c6ca1a285d7e">

as you can see 'monsters' and 'the fall' are missing and then a few are there and then some are missing again, it's weird, just to show you it can be done, here's Umbrella's My TV shows - Progress Shows - I know it's not as easy as just copy pasting some code but maybe Umbrella's code might give you a clue (found this in my email - Trakt in Progress TV shows menu item (Issue #210 from Umbrella github issues)). 

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/26f4efa8-4e3c-499a-ab82-dc93b7303ebe">

Oh jeez, just wanted to include a kodi log so I thought I'd install Fen Light on a clean version of Kodi and what do you know, some missing shows are showing with Estuary Skin but others (like 'the Fall') are still missing. 

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/3afc0e00-ab72-4afe-ab11-08035b86700a">

So skins have some sort of effect apparently, would be great if you could help out here, the progress shows is pretty important, definitely for me but I'm sure for others as well.  

Here's the log from the clean install: 

[kodi.log](https://github.com/user-attachments/files/17138182/kodi.log)

**Comment by Tikipeter** [comment]
It's not a skin issue.

In the examples given above, any show that has been fully watched up until that point (i.e. The Fall) will be in the "Watched" menu rather than the "In Progress" menu. If that show airs a new episode, then once the current cache for the show has expired, then that will be seen and it will appear in the "In Progress" menu.

With the info available (apart from the Monsters instance) I can only guess that that is what might be troubling you.

**Comment by TechXXX** [comment]
Oh jeez didn't even notice that they were fully watched, just saw missing shows from the website...and assumed. Feel free to close this one out, glad it's not a problem this time. Any way to shorten the duration of the Trakt cache expiring so changes will be seen sooner?

**Comment by Tikipeter** [comment]
It's more the caching I do rather than the caching from Trakt. I rely very little on Trakt for these sorts of things. And to keep taking care of TMDb, I can't really lower caching times. There's some logic to caching based on when the next episode will air if that info is available. I'll have a look over that and see if it can be tweaked.

Fen (original) had a setting where you could choose where to place Fully Watched (but still airing) TV Shows. You could choose to display them in "Watched", "In Progress" or "Both". It was one of the many settings I removed when making Fen Light.

I could bring that setting back if you liked? Then you could have the fully watched (but still airing) shows in the In Progress menu.

**Comment by TechXXX** [comment]
Well thanks for offering but I don't see the utility other than satisfying my ocd. If the show is fully watched I have no reason selecting it, none that I can think of anyway. Thanks again.

**Comment by Tikipeter** [comment]
Oh. :)

Imma prob'ly add it back anyway.

Just leave it as default if I do.

**Comment by TechXXX** [comment]
Appreciate ya
