### ISSUE TITLE
Link to tv show Feature

### ISSUE THREAD

**Issue by luchoanas** [Tikipeter/tikipeter.github.io#136]
Hello, I remember in Fen, there was this feature where you can link a folder in cloud storage to a TV show in order for in to show in results. I can’t seem to find it in Fen lite. I got this show in my Real Debrid cloud storage and it doesn’t show in the results. Can you help please?

**Comment by hcgiub001** [comment]
Hey Tikipeter. I'll make this brief , not like the essays I normally do :)
Say I add the torrent for the show Diplomat as a torrent to my RD cloud

then I have this screen where I'm about to click it
![image](https://github.com/user-attachments/assets/84c899d5-8935-474f-b987-9b15401d2cdf)

when I click it and see the show with the groups.
would it be possible to have an extra group but it is the torrent file

this is just a rough sketch
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/80da9e6b-0ade-4fd7-89f8-153c63156ba9">

I think this would make a great addition, sometimes even when you link a show it can't pick it up because of some labelling miss match, and in that case you have very easy access to the file every time. Even though you won't have metadata you can enjoy the show and be assured it's in the right order.

maybe users can have a setting if they want to add this. So many times I wish I had access to the torrent and not confined within TMDB constraints of labelling, raw unedited files.
If this can't be done or you don't think it's a good idea please ignore and looking forward to be able to link files :)
really appreciate your work and your commitment :)
thanks for your consideration
