### ISSUE TITLE
[FEATURE REQ] Save a named preset filter in a selectable list

### ISSUE THREAD

**Issue by colemar** [Tikipeter/tikipeter.github.io#159]
It seems the only way to isolate movie releases with italian audio is to look for "ita" string in the file name.
Therefore every time in the results list I have to push left key, select FILTER BY TITLE, then insert "ita" and confirm.
It would be much more convenient if, for example, pushing left one time a list of named preset filters (saved from before) would appear, and pushing two times the current list of generic filters would appear.
![PXL_20241031_020237588](https://github.com/user-attachments/assets/f20be20c-a9a1-4401-a419-a15b87776580)

**Comment by hcgiub001** [comment]
![image](https://github.com/user-attachments/assets/b12f780a-e2cf-4e9c-a68b-1eb3dce2d7d7)

what if their is a setting in "SORTING AND FILTERING"
that you can add keywords
So you can add the keyword "ita"
(next part is optional
then you assign a number to it (from 1-100) , 100 has highest priority 

You can add other keywords too)

Then in RESULTS SORTING instead of QUALITY,SIZE,PROVIDER
you have 
KEYWORD(S),QUALITY,SIZE,PROVIDER

Now all terms with ita will place at the top then the rest of the results will display below them
If a result doesn't have ita in it's name, then you'll still see the other results and you don't have to press anything.
this has the benefit that you can also use autoplay knowing you have a good chance it will find an italian language source (if their is one)

**Comment by colemar** [comment]
Sure, the solution you explained it is even better! 😎
In fact I already looked for something like this in the results sorting setting, but of course I found nothing.
Thanks

**Comment by colemar** [comment]
Why not?

**Comment by hcgiub001** [comment]
> Why not?

I cam on about 5 months ago and met Tikipeter, he told me doesn't work on his addon more than 3 hours a week. since that time I think he's done 10+ hours a week none stop. Now it's time to rest and some things he wanted to do to make others happy have to go so he can rest and get through the issues that keep popping up. Don't take this personally. I don't think I would want to work on something I won't use or have any enthusiasm for or energy. Think at what we got not what we are missing.

Tikipeter you deserve a big break :)

**Comment by xyzfre** [comment]
> > Why not?
> 
> 
> 
> I came on about 5 months ago and met Tikipeter, he told me doesn't work on his addon more than 3 hours a week. since that time I think he's done 10+ hours a week none stop. Now it's time to rest and some things he wanted to do to make others happy have to go so he can rest and get through the issues that keep popping up. Don't take this personally. I don't think I would want to work on something I won't use or have any enthusiasm for or energy. Think at what we got not what we are missing.
> 
> 
> 
> Tikipeter you deserve a big break :)

Please don't take this personal are you a developer? I see you respond a lot for Tikipeter I was under the impression he was the developer for his add-on.

**Comment by hcgiub001** [comment]
> > > Why not?
> > 
> > 
> > I came on about 5 months ago and met Tikipeter, he told me doesn't work on his addon more than 3 hours a week. since that time I think he's done 10+ hours a week none stop. Now it's time to rest and some things he wanted to do to make others happy have to go so he can rest and get through the issues that keep popping up. Don't take this personally. I don't think I would want to work on something I won't use or have any enthusiasm for or energy. Think at what we got not what we are missing.
> > Tikipeter you deserve a big break :)
> 
> Please don't take this personal are you a developer? I see you respond a lot for Tikipeter I was under the impression he was the developer for his add-on.

No I'm not a developer and should not have said what I did. I'll refrain from doing this again.

**Comment by colemar** [comment]
I see that @xyzfre replied to a post of which I can't see the original.
Anyways @Tikipeter, I am not disappointed.

**Comment by hcgiub001** [comment]
nyaa has an rss feed
https://nyaa.si/?page=rss

looks like this
![image](https://github.com/user-attachments/assets/41c596d9-0e9f-4e55-b857-28ad5fcefce0)

I believe it's using RD api to add the magnet links.
and it will check every interval on the rss feed to see if it's already added it.
I've used it and it almost works perfectly but the developer isn't an anime fan so I didn't want to push him

subsplease also has it's own feed
https://subsplease.org/rss-feeds/

this is an rss feed I created 
https://nyaa.si/?page=rss&q=%5BErai-raws%5D+Mahou+hevc+Tsukai+ni+Narenakatta+Onnanoko+no+Hanashi++1080p&c=0_0&f=0

![image](https://github.com/user-attachments/assets/f22506a4-443c-40b6-883d-f5cabae5ff34)

as you can see, we can create our own list in nyaa, then press the RSS feed and it will give a list in RSS form of the torrents 

if you add this then you would get every torrent easily and fast because you are adding everything to RD network
