### ISSUE TITLE
Next Episodes on Nvidia Shield 

### ISSUE THREAD

**Issue by chrissxuk** [Tikipeter/tikipeter.github.io#173]
I have this addon installed on both a Firestick and Nvidia Shield. Both have exactly the same setup, Kodi version, and Fen Lite version. 

I have authorised and reauthorised Trakt and can see all my Trakt lists but when trying to access next episodes it errors. This only happens on my Nvidia Shield it works perfectly on my Firestick. 

Error logfile: https://paste.kodi.tv/vatewomudo

**Comment by Tikipeter** [comment]
You have a corrupted database.

Try Tools->Database..Maintainence->Check for Corrupt Databases.

If that finds and fixes the database, great. Restart Kodi.

Otherwise you will have to delete the database manually and then restart Kodi. The trakt database if using trakt or the watched database if not. Both found within the userfata folder for Fen Light.

**Comment by chrissxuk** [comment]
Manually deleting the trakt database fixed the problem. Thank you very much for you help.
