### ISSUE TITLE
Potentially unnecessary xbmc.sleep usage?

### ISSUE THREAD

**Issue by bbviking** [Tikipeter/tikipeter.github.io#215]
Apologies for bugging you, I'm sure there's something very simple I'm missing or some scenario that I'm not thinking of but I was wondering if the xbmc.sleep uses was needed in these functions:

real_debrid_api.py - resolve_magnet (except from this line - 'if info_hash in active_list: sleep(1000)')
sources.py - play_file

When I was testing in a bunch of different scenarios, the only difference I could find is that time to start playback could (particularly in situations where it has to attempt resolving on many different sources before a cached one is found) be shortened by multiple seconds by removing them.

My first theory is that they are in place to try and prevent race condition issues particularly present on very low powered devices, but I couldn't see what that would be.

**Comment by Tikipeter** [comment]
Far too long ago for me to remember why the sleep(s) in play_file are there. Sometimes a sleep might get added in testing and then stay there when everything works. Often, but not in this case, small sleeps (100ms, 200ms) are there purely because Kodi was being troublesome, and a small sleep usually fixes that when there is no logical reason for it to be happening. I'll lower the offending sleep in play_file to 200ms and the one in RD before the transfer check to 200ms as well.
