### ISSUE TITLE
Feature request : Randomized Trakt Liked / My List

### ISSUE THREAD

**Issue by nascar999** [Tikipeter/tikipeter.github.io#52]
The random list feature is great, but would there be a way to randomize a specific list from within Trakt Liked and My Lists? Selecting a random list from these categories is great, but would like to be able to choose a list (ie. Top 100 Movies) and have it display those movies in a random order. If this already exists have not been able to find it.

Thank you consideration for for sharing all your work with this great add-on

**Comment by hcgiub001** [comment]
This is done in trakt

open your trakt account on a list
click on a the pencil icon to edit the list
in the default sorting section pick how you want the list to be displayed
<img width="271" alt="Screenshot 2024-07-02 101303" src="https://github.com/Tikipeter/tikipeter.github.io/assets/171574389/178290cb-86c3-4fba-a213-af4ebdc317d0">

Kodi respects the default ordering you set on trakt. best thing is you can have so many options on how you can set each list in trakt and you can have a different sorting for each list you have, one list could be random another you can sort using ratings etc

**Comment by nascar999** [comment]
Thank you for the reply and the included screenshot. This appears to be the ticket for My Personal Lists, but does not seem editable in Liked lists?

**Comment by hcgiub001** [comment]
I don't really use liked lists myself, but yeah it's not an option in trakt.  I think it would be a good feature to have in FenLight.

If have a suggestion. when we enter a list, have a folder at top that shows how the list is organised. when people click the folder, you get options on how to organise the list. then the new default is saved, the option to organise a list in other ways is allowed on trakt but it doesn't make it default 
![Screenshot (30)](https://github.com/Tikipeter/tikipeter.github.io/assets/171574389/9624464c-b98e-479c-90fe-991960fd530e)

**Comment by Tikipeter** [comment]
Whilst you can indeed set the list sort method to "random" on the Trakt website, and FenLight WILL order the list as "random", my memory tells me it will only do this when uncached data is retrieved from Trakt i.e. the random sorting will only happen once when there is a reason to get fresh data for the contents of the list.

Until there is a need to get fresh list data, there will be no subsequent "random ordering" of that list when displayed, it will continue to be sorted as per the very first random sort.

Since that is likely the case, the next update will have `Shuffle Contents Trakt My Lists` and `Shuffle Contents Trakt Liked Lists` in `Random Lists->Trakt`. Use this to make a widget/add to a menu within FenLight, and then each time you enter that list it will be freshly sorted at random.

**Comment by nascar999** [comment]
Awesome, thank you so much
