### ISSUE TITLE
Petition to leave the hat

### ISSUE THREAD

**Issue by minicoz** [Tikipeter/tikipeter.github.io#58]
Fuck the haters, leave the hat tiki

**Comment by hcgiub001** [comment]
I'll use the addon either way. I'm not from USA so I don't care, hate looks cool. I've also had a go at them on reddit but why involve politics. kodi is about movies and this just divides us. It's easy to say fuck haters but having a symbol of something you are against and force it on your audience , what will that accomplish? Tikipeter worked hard on his addon. to me it's the best addon bar none. and I want it to be the best addon. having the hat accomplishes nothing. we don't need arguments.
lets just move on. Tikipeter was able to spread his wishes.
but I'll support Tikipeter whatever he wants to do.

**Comment by Tikipeter** [comment]
The hat wasn't meant to be political, it was purely meant to show my respect to a man who had just come within an inch of...well, you know what happened. It was also meant to be used only in that next update. Again, as a show of support.

I suppose it's reasonable for unreasonable people to assume me using the hat was an "endorsement" or something, and thus was "political", but that's silly. I'd have put a hat up there years ago if that were the case.

Anyway, I'm glad you didn't have a "literally shaking" event when you saw the hat, and I'm sorry that you wanted it to stay. But it was always a one update thing. I thought with what had just happened, people might have shown an ounce of grace. I put too much faith in these people.

They are sick, vile, murderous thugs. Or they're brainwashed by sick, vile, murderous thugs.

That's the reality.

**Comment by Tikipeter** [comment]
Oh, we also must remember that Reddit is not an indication of broader views on ANYTHING.

It is a cesspool of radically far-left, ultra-woke, hive minded drones. If it's not a bot replying to you, that is.

**Comment by hcgiub001** [comment]
I knew you was going to have up for a little while to just show support at this very exceptional time. You could have easily put it up when he started his political campaign if you wanted to.
Glad you won't let it get to you. People are quick to judge others that have given so much to the community.

**Comment by Tikipeter** [comment]
Thanks for that.

It didn't get to me at all. Would have in the past, but not anymore.

Upon reflection, the fact people believed they were "stuck" with the icon means I likely should have left well enough alone. It's like if I were to wear the cap in real life..... if I were to enter someone's home and they asked me to remove it, I would of course remove it. It's their kingdom, their rules.

People's Kodi Homepage should have the same rules I've realized. It's in their house, they own it.

The comment in the changelog was enough to show my support against what happened to him.

**Comment by hcgiub001** [comment]
the difference is you created the rooms in the home, set up the all the plumbing and electrical, insulation, been coming to the home for years and providing any support to issues for free. all they did was put in furniture. If you want to come in to their home for a week with a hat they should keep their own opinions in for a little while and give you some respect. without you they won't have their nice home.
their are two sides to the argument, we owe you some leeway . 
But maybe if you was more clear that you want some prayers to help support someone who almost died and keeping the hat till next update which won't be long. You can't expect them to have average IQ.

**Comment by minicoz** [comment]
@Tikipeter, don't let the clown world win and get their way. If something as stupid as a hat on a logo is triggering these people I say keep it. By you removing the hat, you are letting them win and bully you to get their way. 

Its something as small as a red hat, it doesnt even have a political slogan. Its seriously a joke that so many people get trigger for this, its insane. The party of inclusion, tolerance and acceptance is only accepting when it fits their narrative. I say keep it. 

A father, firefighter and husband was actually assassinated that day. No one is talk about it and if you bend to the whims of these screeching users, they will win and know that they can be just as evil and get their way and suppress any narrative that they dont agree with. 

here is a wall of hate of july 13th. 
[https://july13th.com/hate/](https://july13th.com/hate/)

im tired of the clown world getting its way. Im starting to speak up now.

**Comment by Tikipeter** [comment]
I understand your disappointment, and if my plan was to leave the hat there, trust me the hat would still be there. I suppose you can use the fact that it was VERY crudely pasted on top of the fen light logo as proof that I meant it to be temporary.

These people hold zero power over me. I'm not sure if they did at one time in society generally, maybe so, but certainly not at this point in time. I'm not "retreating" by removing the hat. The hat was always meant for one update. I suppose I could have changed my mind with the backlash and kept it there, but from what I read all the nappy wetters took off and uninstalled anyway. So they'd never know.

The fact is if I left it there, I'd be doing it because I want THEM to think a certain way about me and what the hat meant. I don't give a damn what they think of me. They may think they won, who cares? Apathy towards them has to be absolute. If I left the hat there I'd be doing it for them, and I'd still be being controlled. I did what I wanted, and removed the hat when I wanted.

The issue is I AGREE that Kodi addons shouldn't be used for political purposes. My thoughts were this was NOT a political purpose. It was a show of respect and admiration for a man and a disgust for what had happened to him. The fact these people, only a day after the events, could not even have the humility to realize that might be the motive was not really a surprise. But I had hoped for better.

As you may have noticed, the rhetoric around Trump has gone straight back to how it was. The same rhetoric that made that little fucker think he was a hero for doing what he did.

Wear your MAGA in public every chance you get. Everywhere. That is the best thing we can do.

If I ever change my mind on Kodi being used for political purposes (doubtful) I will have an icon so magnificently MAGA their little brains will seize up. But that is not what I want to do.
