### ISSUE TITLE
Open Movie Collections Instead When Available

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#62]
This is funny. I've been wanting to ask you to implement this for a week now. even down to "the movie selected will be highlighted"
Thankyou so much!

1/ bug
it doesn't highlight the movie in the collection but one less in the collection
below I clicked deadpool 2 but deadpool one is highlighted
<img width="1280" alt="new" src="https://github.com/user-attachments/assets/356f4673-f8b8-4e53-b04b-262953256a23">

2/feature request.
I love this feature but I don't have extras enabled, please could you allow users that don't have extras enabled to have access to this feature?
(also those that haven't enabled extras are even less likely to know the movie might be part of a collection because to otherwise know a movie is part of a collection they would have to bring up context menu on every movie, some users don't have buttons to bring up context menu and don't even know that long press brings up context menu)

3/can we have an option in setting that allows us to indicate a movie is part of a collection. I have one suggestion that could work
when you have folders in list, an icon is placed before the title to indicate it's a folder (like so)
![Screenshot (112)](https://github.com/user-attachments/assets/3a0f17f9-552c-459e-bc25-5fa924288d0d)

since a movie that is part of a collection is also a folder, you could have an icon placed before a movie. something like this

before icon

![Screenshot (113)](https://github.com/user-attachments/assets/11b96f72-b1c9-4d80-95fc-7789d4274649)

after icon

<img width="1280" alt="with collections" src="https://github.com/user-attachments/assets/6409f544-d90d-4950-9891-287cda89e9ea">

again this would be a toggle user can set, but to me it's a nice indication that the user would know when we are going to collections folder (some movies aren't obvious its part of a collection)

this is the icon I'm using 
![1675411-200](https://github.com/user-attachments/assets/7d6265ad-a1ae-4cd3-a1fb-d5d02731ecb7)
taken from this collection
https://thenounproject.com/icon/collection-2221162/
(right click save)
doesn't have to be this icon

here how it looks on the popular Nimbus skin

before icon
![Screenshot (114)](https://github.com/user-attachments/assets/d480da90-1b46-4c7c-991e-2e3e3d7fb12d)

after icon is added

<img width="1280" alt="mission impossible collections" src="https://github.com/user-attachments/assets/930a4458-e8fb-476d-b6e9-bbcfb9d2a49c">

It's subtle and doesn't affect the great aesthetics of Nimbus (thought's @ivarbrandt ?) 
and user can not have this toggled if they don't want, and it won't be skin dependent.

if you are not fond of an icon, you could use another indicator like underscore on the title. or if the icon is to much going on you can just have a rounded rectangle instead to make it cleaner?

Again thanks for this feature, I really really love it!

**Comment by Tikipeter** [comment]
1. BUG: I'll remove the auto highlight next update. On slower hardware I'd need to add a sleep time before it, and also you've seen the playing of a Trailer through the skin also messes with it.
2. This will be done next update. I will have to change the settings around a bit so it makes sense what you want to have happen when you select a movie.
3. Unfortunately, Fen Light has to be compatible with more skins than just Nimbus/Fentastic. As such, changing the listitem label to something other than the movies title COULD cause issues for skins that use that instead of the listitem property they are meant to use when displaying the title of the movie. It IS possible it wouldn't cause an issue to have the listitem label as something different, but even in that case I'm pretty sure I would need a special type of image for it to display as part of a label value. The image you included would not work I am sure. If you had some other, less good looking idea as to how the movies belonging to a collection could be distinguished (for example adding a `[C]` or other alphanumeric value to the label, then I could implement that and keep an eye out for any skins not displaying the label correctly. But there's a 50/50 chance I would end up having to remove it. But we could try.

**Comment by hcgiub001** [comment]
I did a search inside FENlight for
Deadpool 2
{ Deadpool 2 }

both searches produced the same movies, so seems this would be an elegant way to denote a set while not messing anything up

**Comment by Tikipeter** [comment]
We'll try it with the brackets and see how it goes.....

**Comment by hcgiub001** [comment]
yay, if the bracket gives issues, you could just have hyphen at the beginning like
- Deadpool 2

hyphens are already used so they don't pose a problem already. just any indicator would do , but I'm hopeful the curly brackets would be good. thanks. how about having this as a toggle for those that don't want it? if not it's fine :)

**Comment by hcgiub001** [comment]
I'm trying out Arctic Horizon 2, damn it's pretty badass, came across this view
![Screenshot (175)](https://github.com/user-attachments/assets/44bab8f4-13e6-4f19-9a26-00d8a7c85207)

having anything in the title is going to look bad. I didn't consider all skins. I think it's fine leaving the title as it is. if a skin wants to make use of adding an icon, they have a list item to work with.

having anything in title would make it ugly for skins like AH2. Once you had a chance to complete 2/ , go ahead and close the issue thanks
