### ISSUE TITLE
Request.

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/tikipeter.github.io#66]
Hey Peter

Thanks for the cool addition that is in it now, the addon is getting better and better. Thank you for that.

But question, I know you're not crazy about requests but good no you have yes you can get.

I have a lot of series where specials are broadcast. Is it perhaps possible to bring the option back in Fen light?

Thank you in advance.

**Comment by Tikipeter** [comment]
I'll add the "specials" back, but they really serve no useful purpose apart from seeing that they exist. Nearly all episodes will garner zero sources, and you won't be able to mark them as watched/unwatched.

I don't see the point really. But it will be in nnext update.

**Comment by Jcloak** [comment]
Specials are useful sometimes. "Invincible" recently released a special episode between seasons which definitely had sources available.

I agree that 95% of the time specials are useless though, so for that reason I think it is better to display that season at the end of the lists.

I temporarily updated the code on my machine with this sorting to put it at the end, but I was also thinking naming it "Specials" instead of "Season 0" might be a good idea too.

```python
season_data.sort(key=lambda k: (k['season_number'] == 0, k['season_number']))
```
