### ISSUE TITLE
[Feature Request] Folders for IMDB recommendations for 'Based on recently watched' movies and TV shows

### ISSUE THREAD

**Issue by OfficerKD637** [Tikipeter/tikipeter.github.io#93]
Hi Peter!

Hope you've been doing well!

I've been loving the IMDb 'More Like This' a lot! The recommendations are a lot better than what TMDb provides.

I was wondering if it'd be possible to add folders inside the Movies and TV Shows categories for IMDb recommendations 'Based on Recently Watched'? 
Currently, the 'Because You Watched...' sections have separate subfolders with recommendations based on specific movies/shows that you've previously watched. This is great for allowing more control but I couldn't find a way to create a home screen widget that'd automatically grab the recommendations from the most recently watched item.

So I was hoping for a more simplistic/automated approach with two folders (for movies and tv shows respectively) that would have recommendations for the most recently watched item. This way I could have a widget point to that folder and it'd update automatically as I watch new things. 

Some more wishful thinking would be instead of only using the most recently watched movie/tv show, we could maybe have a random seed pool of the last 3-5 watched items that the recommendations could cycle through? Not sure if this is a better approach or just sticking with the last watched item would be more consistent.

Let me know what you think.

**Comment by Tikipeter** [comment]
On the list. :)

**Comment by OfficerKD637** [comment]
Woohoo!! Thank you so much Peter! It's like Christmas came early!

**Comment by Tikipeter** [comment]
I've got this ready for next update.

Firstly, there will be a new setting: Settings->Content->General->"Service used for Because You Watched". With this setting, you can choose whether Recommended (TMDb) or More Like This (IMDb) services are used for the Because You Watched results. Sounds like you would set this to "More Like This (IMDb).


Secondly, I have added a "Because You Watched" section to the Random folder. I realize, re-reading your request, that I may have implemented this slightly wrong though.
Currently, I take a random 3 from the last 5 movies/episodes you have watched, collect all the recommended titles for those 3, and then select a random 20 from that list of results. This means the final list will have some recommendations from all 3 of those randomly chosen movies/episodes.

I can definitely change it to show all recommendations from 1 of the last 3 or 5 movies/episodes watched. Which I think is what you're asking for. It would actually be easier. So then the randomness would purely be what the 1 seed will be, rather than that plus which final results are chosen.

Let me know if you want me to change it. No hassle.

**Comment by OfficerKD637** [comment]
Wow!! This is wonderful! Thank you so much, Peter!! I cant believe we get the option to choose the recommendation service! This is so awesome!

Yes, it'd be great if you could kindly implement the second variation. I know you said it'd be easier but I can't even imagine how much work has gone into implementing this.
I really appreciate everything!

Can't thank you enough!!

**Comment by Tikipeter** [comment]
I'll change it to work that way.

**Comment by OfficerKD637** [comment]
You're the G.O.A.T!! Thank you thank you thank you!!
